### ISSUE TITLE
Library Not compatible with older android version below Android  11 like Android 7.

### ISSUE THREAD

**Issue by ali-digizonelabs** [Surile/react-native-sunmi-printer#61]
My app crash when I run the app in a simple SUNMI, with android 7. If anyone can help please lemme know.

**Comment by rufique** [comment]
Have you managed to find a work around for this. I am running the library on  Sunmi v2 pro with expo sdk 52, but i get an error on this method

 /**
   * 包事务打印专用接口
   *
   * @param tranBean
   */
  @ReactMethod
  public void commitPrint(TransBean[] tranBean) throws RemoteException {
    printerService.commitPrint(tranBean, innerResultCallback);
  }


com.facebook.react.bridge.ReactNoCrashSoftException: raiseSoftException(getOrCreateDestroyTask()): handleHostException(message = "Error: Exception in HostObject::get for prop 'SunmiPrinter': com.facebook.react.internal.turbomodule.core.TurboModuleInteropUtils$ParsingException: Unable to parse @ReactMethod annotation from native module method: SunmiPrinter.commitPrint(). Details: Unable to parse JNI signature. Detected unsupported parameter class: com.sunmi.peripheral.printer.TransBean[], stack:

**Comment by shamim261** [comment]
still getting this issue: 
Exception in HostObject::get for prop 'SunmiPrinter': com.facebook.react.internal.turbomodule.core.TurboModuleInteropUtils$ParsingException: Unable to parse @ReactMethod annotation from native module method: SunmiPrinter.commitPrint(). Details: Unable to parse JNI signature. Detected unsupported parameter class: com.sunmi.peripheral.printer.TransBean[]
	at com.facebook.react.internal.turbomodule.core.TurboModuleInteropUtils.convertParamClassToJniType(TurboModuleInteropUtils.kt:138)
	at com.facebook.react.internal.turbomodule.core.TurboModuleInteropUtils.createJniSignature(TurboModuleInteropUtils.kt:97)
	at com.facebook.react.internal.turbomodule.core.TurboModuleInteropUtils.getMethodDescriptorsFromModule(TurboModuleInteropUtils.kt:69)
	at com.facebook.react.internal.turbomodule.core.TurboModuleManager$Companion.getMethodDescriptorsFromModule(TurboModuleManager.kt:403)
	at com.facebook.react.internal.turbomodule.core.TurboModuleManager$Companion.access$getMethodDescriptorsFromModule(TurboModuleManager.kt:389)
	at com.facebook.react.internal.turbomodule.core.TurboModuleManager.getMethodDescriptorsFromModule(TurboModuleManager.kt)
	at com.facebook.jni.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:755)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.kt:21)
	at android.os.Looper.loop(Looper.java:154)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$Companion.startNewBackgroundThread$lambda$1(MessageQueueThreadImpl.kt:175)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$Companion.$r8$lambda$ldnZnqelhYFctGaUKkOKYj5rxo4(MessageQueueThreadImpl.kt)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$Companion$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:761)
